// ============================================================
// components/FallbackBadge.tsx
// Subtle, non-alarming indicator shown when a response was
// generated via the Grok (xAI) backup provider instead of
// the primary Gemini service.
//
// Design intent: easy to miss if you're not looking, but
// honest. Does NOT make the UI look degraded. Only shown
// when viaFallback === true; renders null otherwise.
// ============================================================

"use client";

interface FallbackBadgeProps {
  visible: boolean;
}

export default function FallbackBadge({ visible }: FallbackBadgeProps) {
  if (!visible) return null;

  return (
    <span
      title="Gemini was temporarily unavailable. This response was generated by the backup AI service (xAI Grok). Quality is equivalent."
      aria-label="Generated via backup service"
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "0.3rem",
        fontSize: "0.68rem",
        fontWeight: 500,
        color: "var(--color-text-muted, #94a3b8)",
        background: "rgba(148, 163, 184, 0.08)",
        border: "1px solid rgba(148, 163, 184, 0.2)",
        borderRadius: "4px",
        padding: "0.15rem 0.45rem",
        letterSpacing: "0.01em",
        marginLeft: "auto",
        cursor: "default",
        userSelect: "none",
      }}
    >
      <span
        aria-hidden="true"
        style={{
          width: 5,
          height: 5,
          borderRadius: "50%",
          background: "currentColor",
          opacity: 0.6,
        }}
      />
      Generated via backup service
    </span>
  );
}
